library(GAPR)
library(readr)

bank <- read_delim("C:/Users/USER/Documents/GitHub/psychic-spoon/DataSet/bbank_no_y.csv", delim = "\t", col_names = TRUE, show_col_types = FALSE)

bank <- as.data.frame(lapply(bank, function(x) as.numeric(as.character(x))))

n_original <- rownames(bank)
x_original <- colnames(bank)

respond = GAP(
    data = bank,
    row.prox = 'jaccard',
    col.prox = 'jaccard',
    row.order = 'average',
    col.order = 'average',
    border = TRUE,
    PNGfilename = 'bank的GAP.png',
    show.plot = TRUE,
    exp.row_order = TRUE,
    exp.row_prox = TRUE
)

rowprox <- as.matrix(respond$row_prox)
doc_order <- respond$row_order
doc_numbers <- n_original[doc_order]
doc_order
# 分群：可視需要切成 K 群（例：2 群）
doc_cluster <- cutree(hclust(as.dist(1 - rowprox)), k = 8)

doc_numbers[doc_cluster == 1]
doc_numbers[doc_cluster == 2]
doc_numbers[doc_cluster == 3]
gap_cluster_df <- data.frame(filename = doc_numbers, gap_cluster = doc_cluster)
write.csv(gap_cluster_df, "gap_cancer_clusters.csv", row.names = FALSE)
cat("✅ GAP 分群結果已儲存為 gap_icancerclusters.csv\n")


